Fix ARM internal compiler error reload1.c:3633 compiling Earth
ARM GCC 4.6 experiences ICE when compiles Earth in debug build
  libs/evll/database/quadtreecachetype.cc:237:1: internal compiler
     error: in elimination_costs_in_insn, at reload1.c:3633

The reason is that ARM back-end expects wrong operand type
sign-extend from char.

Back port fix from
  http://gcc.gnu.org/bugzilla/show_bug.cgi?id=50099

Change-Id: Ia235b76c6f0bada472a741a763d087789a41db8e